

version: "3.8"
services:
  postgres:
    container_name: learn-go-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .docker.env
    networks:
      - postgres

networks:
    postgres:
        external: true